export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

// pages/about.tsx
import React from 'react';

const contact = () => {
return (
  <div>
    <h1>Contact</h1>
    <p>This is the contact page.</p>
  </div>
);
};

export default contact;
