export const metadata = {
    title: "About",
    description: "Generated by create next app",
  };

// pages/about.tsx
import React from 'react';

const About = () => {
  return (
    <div>
      <h1>About Page</h1>
      <p>This is the about page.</p>
    </div>
  );
};

export default About;
